### ISSUE TITLE
Unable to view records in unreviewed tab

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#1]
Hi Dave, I was compiling a list of all the unreviewed records by enum district and I noticed one that needed a simple edit.  When I tried to open it, and others, I got the message 
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.
In case the url helps- https://www.historyforge.net/census/1930/unreviewed/14787
I can access and open the records when I go back to all records  and search for them.
Thanks,
Eve

**Comment by dfurber** [comment]
Good catch. I moved some buttons around so it won't be an issue.
