### ISSUE TITLE
1940 supplemental record-remove NY as default Pob mother/father 

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#101]
I'm removing this from each record as I review so if you could get rid of this as a default soon I'd appreciate it.

**Comment by dfurber** [comment]
Doing it for pob, pob mother, pob father, for 1900, 1910, 1920, 1930, and 1940. @EveSnyder

**Comment by EveSnyder** [comment]
Would it be possible to keep New York as the default in New York but code it so that the default is whatever state the HistoryForge project is in.  So for example if Oberlin, Ohio joins us as a testing partner could the dfefault be Ohio?  It takes so much less time to enter the records if you don't have to type that in.  
The reason I wanted it removed from the supplemental record in 1940 was different-that was because it was the only fields in the supplemental records which were filled out and there are only 2 supplemental records per page so it looks like the supplemental record has been filled out but for only the pob father/mother.

**Comment by dfurber** [comment]
@EveSnyder Yes trying to solve two problems at once. But now I see that I didn't actually make a setting for default POB, nor did I make it autofill that setting for new records. That check is in the mail now.
