### ISSUE TITLE
HF Auburn-data entry pages

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#138]
The data entry pages for each census year need to have the county and city changed to reflect Cayuga and Auburn and the Locality needs to be changed-they might add other localities so keep but change to Auburn.

**Comment by dfurber** [comment]
Done! Notice the new Settings page on the Admin menu.

**Comment by EveSnyder** [comment]
Ooh nice!!  One thing should the email from the contact form go to us? What if it is a local question?

**Comment by dfurber** [comment]
@EveSnyder I think you should update the settings with an email that goes to the Auburn people. (Settings is new this weekend.)

**Comment by EveSnyder** [comment]
Okay yes I saw that, thanks!
