### ISSUE TITLE
Can you make it so that if someone enters a period in the occupation or industry code it doesn't save

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#156]
For consistency I ask the transcribers not to include a period after abbreviations in occupation or industry but they don't always remember. Could you code it to not take the period?

**Comment by dfurber** [comment]
@EveSnyder Instead I've made it strip out the period. But I didn't fix it for existing records. Doing that now.

**Comment by EveSnyder** [comment]
Thanks!
