### ISSUE TITLE
hint-TAB

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#16]
The hint that comes up about tabbing-would it be possible for that to go away after someone starts entering a record because it hides some of the fields, especially for the users who use HF not full screen

**Comment by dfurber** [comment]
For the haters there is now a button on the bottom right, opposite the save button, that will turn the hints on and off.

**Comment by EveSnyder** [comment]
That only works for an individual record.  When we finish a record and start another we have to scroll down to the bottom and turn it off again.
