### ISSUE TITLE
Can't save Jrs

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#161]
Record won't save for a child with the same first and last name as their father or mother.  
Last name box highlighted with he message:
Last name A person with the same street number, street name, last name, and first name is already in the system.

**Comment by dfurber** [comment]
@EveSnyder You'll need to add Jr as a suffix to the name.

**Comment by EveSnyder** [comment]
In the name field itself or in the suffix field?  I tried to put it in the suffix field and it wouldn't save so I added to the name field which worked.  If we need to use that as the workaround let me know so I can tell our transcribers.

**Comment by dfurber** [comment]
@EveSnyder You'll have to explain as it seems to work for me.
