### ISSUE TITLE
1910 Census-change records listed as Mixed/Mulatto to Mulatto

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#168]

**Comment by dfurber** [comment]
@EveSnyder Currently changing for one year changes for all years that have "M" as a choice. I think that's why it says "Mixed/Mulatto" - to cover the cases where M is "Mixed" vs "Mulatto" when they both mean the same thing.

**Comment by EveSnyder** [comment]
Bob said to change it to Mu - Mulatto (like 1920).

**Comment by dfurber** [comment]
Closing because I did it in December but forgot to close
