### ISSUE TITLE
Taber St-street name and numbering issue which defies street name conversion

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#170]
Taber St used to be the 800-900 block of W Green St.  The street name conversion only handles when the name changes for the entire street not portions of it. I realize this is a more involved issue to fix.

**Comment by dfurber** [comment]
What if I add the house number to the street conversion feature? So you could convert 801 W Green St to 101 Taber St... You'd have to add each address unfortunately.

**Comment by EveSnyder** [comment]
If you did that would I only have to enter the house numbers on W Green/Taber or would that mean that in general I would have to enter the house numbers?  Adding house numbers to the street conversion feature could help because I have run across some street numbering changes.

**Comment by dfurber** [comment]
It would mean that each converted house number would get its own "street conversion" entry, which could be tedious. Since that means an exception for each building, I'm thinking of a way to add an "also known as" address to buildings.

**Comment by dfurber** [comment]
I'm adding the house number for now because it is the easiest solution but I don't like it as a permanent solution because it will swell up the number of street conversions to be unmanageable.
