### ISSUE TITLE
Transcribers are currently having a problem with building drop down menu

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#174]
Several transcribers are reporting issues with the building drop down menu.  When they click it no buildings appear (even though there is a building).  I've been trying to get them to give me enough detail to discern a pattern so you can fix the problem.  From what I can tell this happens at least on the very first record someone enters in a session.  For some that's it, for others it seems to be happening the first time they add a new record in a family.  Some report that they can save the person record and go back and edit it to add the building at that stage but in some cases that doesn't work - E Spencer seems to be having a big problem with that but I don't think its limited to this street.

**Comment by EveSnyder** [comment]
I wasn't able to get the building dropdown menu to work at all today.

**Comment by dfurber** [comment]
I see what happened there. Fix is on the way up now.

**Comment by EveSnyder** [comment]
I tried and it didn't work.  
https://www.historyforge.net/census/1900/8760
https://www.historyforge.net/census/1900/8757
