### ISSUE TITLE
Us = US, Dpw = DPW abbreviations under industry wacky

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#175]
I'm guessing this had to do with when you coded it so the first letter of each word in occupation and industry would be capitalized.  Now the letters after are lower case as in Us instead of US or City Dpw instead of City DPW.  I tried to change them to uppercase on HF and it saved them as lowercase.

**Comment by dfurber** [comment]
I can add exceptions for acronyms - please let me know of any more.

**Comment by EveSnyder** [comment]
WPA, NYA, CCC, GLF, RR, MD, NY, NYS, PO.  These are what have been entered so far.  For some reason the CCC and MD entries don't seem to have a problem but I'm including them as acronyms just in case.  Is there anyway you could fix the acronyms already entered?

**Comment by dfurber** [comment]
The reason is that I had set it so that if the upper case version of the item was the same as the item, to leave it. So an entry that is only the acronym would stick but it it was mixed then it wouldn't.
