### ISSUE TITLE
Description/Notes in building records-first letter of each word capitalized, no periods

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#181]
This is likely an unintended consequence of my requests to start the first letter of each word with a capital letter and remove the period in multiple fields on the data entry page for the people records but it looks weird in the building records. For example-https://www.historyforge.net/buildings/5807

**Comment by EveSnyder** [comment]
Also check out the building name displayed in that buillding record.  The building record was created by merging the two buildings in the building name field and then changing the address to reflect the current street address according to https://pocketsights.com/tours/place/109-Barton-Place-10893

**Comment by dfurber** [comment]
Oops! I made it stop going forward, and since I save a version with each change, it should be possible for me to retrieve the puncuated descriptions and annotations of the buildings.
