### ISSUE TITLE
building markers on filtered map take you to a blank screen

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#182]
If you go to a building record through The Forge the building markers take you to the building records but if you go in by filtering the records and then map it the building markers take you to a blank screen.

**Comment by dfurber** [comment]
Not sure I follow - or at least my attempts to follow work as expected. Please tell me what browser, what filters, maybe a screen shot? @EveSnyder

**Comment by dfurber** [comment]
Ok I think I see it now.

**Comment by dfurber** [comment]
So what I actually discovered is that while I was adding more details about the building to the building display in the sidebar, I got the same blank screen behavior. Turned out it was because of a javascript error on the page, from what I was just doing. Meaning, that's what happens when there a javascript error, but my error wasn't your error because it was code I was just working on. That leaves me curious again which browser you were using...

**Comment by EveSnyder** [comment]
I was using chrome when it happened over the course of a few days, then today it happened to Bob, I'm not sure what browser he uses but I can ask.

**Comment by EveSnyder** [comment]
It just happened to me in safari as well.  I'll take a video and email it to you.

**Comment by dfurber** [comment]
If you take a video please open the dev tools (in windows, it’s the far-right button that brings up “new tab”, “new window”, select “more tools” then “developer tools”.

But I just added a javascript error notifier so I might get some cryptic level of notice as to what the error might be.

**Comment by EveSnyder** [comment]
Developer's tools?  Sigh.  I took a video but if its helpful I could send you a zoom link so I can share my screen with you.

**Comment by EveSnyder** [comment]
Wait now I see the thing that says I can upload mp4 and mov files to this message but the video is 31 mb so I can't

**Comment by dfurber** [comment]
Love it.

**Comment by dfurber** [comment]
Or just tell me what filters you had going...

**Comment by EveSnyder** [comment]
Just sent the video via email along with the filters 1900 census filtered on ED 156.  Also I tried again with the 1900 census and did not get any javascript error notification but maybe you did?

**Comment by dfurber** [comment]
Yep a picture was worth a thousand words.

**Comment by EveSnyder** [comment]
Excellent!

**Comment by EveSnyder** [comment]
Cause my video probably isn't.  Lol!

**Comment by dfurber** [comment]
Fixed it! (If you see more blank screens, it means it's a different error.)

**Comment by EveSnyder** [comment]
Thanks!
