### ISSUE TITLE
Unhoused person not listed as unhoused and somehow linked to the wrong building

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#183]
I've tried to explain this issue before unsuccessfully but hopefully this example will help.
I mapped the 1940 census to find outliers 
https://www.historyforge.net/forge?commit=Map+It&fs%5B%5D=census_scope&f%5B%5D=street_address&f%5B%5D=locality&f%5B%5D=family_id&f%5B%5D=name&f%5B%5D=relation_to_head&f%5B%5D=sex&f%5B%5D=race&f%5B%5D=age&f%5B%5D=marital_status&f%5B%5D=pob&f%5B%5D=occupation&f%5B%5D=industry&scope=on&people=1940

one of the outliers is the building 508 N Aurora which you can see randomly hanging out by itself in Fall Creek  When you go to the building record https://www.historyforge.net/buildings/3275 
and look at residents in 1940 you find Vincent M Couch.
When you go to Vincent's record https://www.historyforge.net/census/1940/3756
his address is 508 S Aurora and when you open his record you can see that he is not attached to any building-not 508 N Aurora.
So somehow the system is randomly(?) attaching people to buildings.
In addition, Vincent M Couch is not on the unhoused list even though he is not actually attached to a building (at least not in his individual record though obviously somehow on the backend he must be).  

I've seen this before where unhoused people are somehow linked to the record for the building on the opposite side of the street, i.e. if they live at 206 E Buffalo they get attached to 206 W Buffalo.

**Comment by dfurber** [comment]
Well the person is "housed" if they are attached to a building. Is it possible that the transcriber chose the N Aurora building instead of S Aurora?

**Comment by dfurber** [comment]
I just changed that Mr Couch's building. I think what happened is this. Once upon a time the N Aurora building showed up on the list. Jesse chose it by accident. Later on we refined the building dropdown not to include N Aurora for a S Aurora address. So it looks "unhoused" on the edit form because N Aurora isn't on the list. But it's really just mis-housed.

**Comment by EveSnyder** [comment]
Okay I'll let you know if I come across any others but hopefully I won't.
