### ISSUE TITLE
Would it be possible to chose basemaps for the building record windows from a layer control?

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#190]

**Comment by dfurber** [comment]
Yes it would be possible. I have to upgrade the building record map thingie soon anyway. I'll do this then.

**Comment by dfurber** [comment]
Done! I removed the opacity slider thing but maybe I should put it back...

**Comment by EveSnyder** [comment]
It would be helpful if you could add back the icon in the top right of that map window that allowed you to toggle full screen view.  That made it much easier to move buildings.
