### ISSUE TITLE
new Oberlin HF users are not able to change their passwords

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#192]
The initial few (2?) accounts for Oberlin HF that Bob and I assigned worked but since then anyone who logs in is not able to change their password.  They can, however, continue to login with the temporary password.

**Comment by dfurber** [comment]
Please help me diagnose as I see no relevant error messages. How are they attempting to change their password and what messages do they receive? Thanks! @EveSnyder

**Comment by EveSnyder** [comment]
They are given a login and temporary password and told to sign in with the temporary password but then update their password with a new one specific to them.  When they tried that they were given an error message in red in the bottom right corner of the screen which says "sorry you do not have permission to do that". They could, however login and  work with the originally assigned password.

**Comment by dfurber** [comment]
Thank you. Also I changed the "add new user" to an invitation system so you don't have to set a temp password. Instead they'll get an email, click on the link, and choose their password.

**Comment by EveSnyder** [comment]
Ooh nice, thanks! So if you use that you put their email address under email obviously but what goes under login?
