### ISSUE TITLE
Emergency-no one can save records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#196]
We are doing a training and no one can save their records, but says we're sorry something went wrong.

**Comment by dfurber** [comment]
Not getting errors - which HF? you may need to specify that going forward so I know where to look @EveSnyder

**Comment by EveSnyder** [comment]
Oberlin

**Comment by dfurber** [comment]
Does the record you are trying to save have an address? @EveSnyder

**Comment by EveSnyder** [comment]
They all do.  This happened to about 3 groups of people

**Comment by dfurber** [comment]
Can you do it again just to trigger the error? @EveSnyder

**Comment by EveSnyder** [comment]
Yes

**Comment by EveSnyder** [comment]
Someone just clicked save did you see anything?

**Comment by dfurber** [comment]
Yep it's angry that a postal code is missing.

**Comment by EveSnyder** [comment]
Its 44074
Let me know when its fixed

**Comment by dfurber** [comment]
I think this emerged when I made 14850 no longer be the default zip code. Now it doesn't have one at all.

**Comment by EveSnyder** [comment]
Is it fixed?

**Comment by dfurber** [comment]
No I have to think it through

**Comment by dfurber** [comment]
Try again?

**Comment by EveSnyder** [comment]
Yes! Thank you!

**Comment by dfurber** [comment]
Apologies if it doesn't geocode - I'll have to fix the building defaults more thoroughly. The issue is that the census form doesn't have city state or zip, so hard to create a building from the address without it except with the defaults.

**Comment by EveSnyder** [comment]
Thanks for getting it done for now.

**Comment by dfurber** [comment]
I've added a setting for postal code that will do the thing for the buildings. It will be up after while.
