### ISSUE TITLE
Multiple default ZIP codes?

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#197]
The Elmira project coordinator let me know that the 14901 postal code for Elmira only covers part of the city.  She mentioned 14904 and 14905 but I googled it and it looks like there might be others.  Not sure which ones were correct or if you need to address that on HF.

**Comment by dfurber** [comment]
Yeah this is an issue.

**Comment by EveSnyder** [comment]
I noticed that now when I add a building by hand I have to enter the city, state, and zip which will help a little.

**Comment by dfurber** [comment]
Actually closing because when you add a building we have no way to know which modern zip code it's in. Also not sure how much it matters except possibly for geocoding.
