### ISSUE TITLE
Oberlin logins from before you changed the system with problematic passwords

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#200]
Oberlin has several users from before you changed the system to inviting people to join HF who all have the temporary password initially assigned (the original "password").  They can login with that password but if they try to change it they get the message that they don't have permission to do that.  We tried disabling their accounts and sending them new invitations but because the email addresses are the same that didn't work.  Is there a way to make it so they can change their passwords?  I guess you can't delete the accounts and start fresh because they have records attached.

**Comment by dfurber** [comment]
I think it works now, at least I took away all my roles and had no trouble changing my password.
