### ISSUE TITLE
Can't edit these records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#202]
In all cases attempts to edit resulted in the white screen with the We're sorry something went wrong message.
Auburn HF-
https://auburn.historyforge.net/census/1910/498 (Laura M. Bailey - need to add Sex- F)
https://auburn.historyforge.net/census/1910/492 (Mary Hughes - need to assign Race - W)

Oberlin HF-they had a similar problem with this record but when I went to retrieve it to add it here I was able to edit it now though they hadn't been able to before.
https://oberlin.historyforge.net/census/1910/103

**Comment by EveSnyder** [comment]
For Elmira HF-
https://elmira.historyforge.net/census/1910/230 
https://elmira.historyforge.net/census/1910/361

**Comment by EveSnyder** [comment]
Also these-
https://auburn.historyforge.net/census/1910/801 
https://auburn.historyforge.net/census/1910/797
https://auburn.historyforge.net/census/1910/1269

**Comment by dfurber** [comment]
They are records not  matched to people, which surfaced an unrelated problem now fixed.
