### ISSUE TITLE
Can't edit Adding MacHines under Industry to correct to Adding Machines

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#203]
I was just notified tht Auburn was having the same problem

This might be related to that last name starts with Mac because I pulled up all the records with Adding Machines as industry tol see if I could fix the incorrectly spelled ones and I noticed a record with the profession MacHinist-https://www.historyforge.net/census/1940/8159
The other Adding MacHine records:
https://www.historyforge.net/census/1940/6368
https://www.historyforge.net/census/1940/81
https://www.historyforge.net/census/1940/8628
https://www.historyforge.net/census/1940/5415
https://www.historyforge.net/census/1940/8629

**Comment by dfurber** [comment]
You can change it now. Notice the new bulk update tool.

**Comment by EveSnyder** [comment]
I tried to use the bulk update to fix MacHinist in 1940.  When I selected Bulk Edit, then Care to start? it took me to a screen with the header Start Bulk Update for 1900.  It takes you to bulk updates for 1900 when you try to bulk edit records in the 1910-1940 censuses.

**Comment by dfurber** [comment]
Try again please

**Comment by EveSnyder** [comment]
1940 - I got as far as choosing occupation as the field to update and I got the message we're sorry something went wrong.

**Comment by EveSnyder** [comment]
Same thing when I tried to change residence 1935 town. However, when I tried last name and clicked submit field it took me to a page with the header Finalize bulk update for 1900

**Comment by dfurber** [comment]
Yes, please try again.

**Comment by EveSnyder** [comment]
I tried to change Last name from Degroat to DeGroat.  I didn't check the solemnly swear box.  It said it changed it anyway but it didn't.  When I tried to edit the record it then gave me the we're sorry something went wrong message. I'll try other fields now.

**Comment by EveSnyder** [comment]
I was able to change occupation MacHinist to Machinist but then when I tried to view and edit an individual record I got the we're sorry something went wrong message.

**Comment by EveSnyder** [comment]
First name LeRoy to Leroy worked but again same message when I tried to view and edit

**Comment by dfurber** [comment]
Please stop for a moment and let me catch up.

**Comment by EveSnyder** [comment]
Oops sorry

**Comment by EveSnyder** [comment]
the last one I tried to change was residence 1935 town from Same house to Same House.  It was trying to update 874 records that's when I got the blue screen and presumably you wrote that comment

**Comment by dfurber** [comment]
Okay now try

**Comment by dfurber** [comment]
Closing because I think we have this one under control, and side effects are (rightly) showing up as their own issues.
