### ISSUE TITLE
Remove greyed out for naturalization status if foreign born isn't checked

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#205]
Our definition of foreign born does not include those who are American citizens through their parents, therefore we want people to be able to check Am Cit without checking foreign born. For 1940 Census.

**Comment by dfurber** [comment]
For 1940 only or across the board?

**Comment by EveSnyder** [comment]
It should be removed for 1940 only-that is the only year which includes AmCit under Naturalization status.  It is currently only greyed out for the 1900 census but should be greyed out for the 1900-1930 censuses.

**Comment by EveSnyder** [comment]
For 1910 both Year immigrated and Naturalization should be greyed out
For 1920 Year immigrated, Naturalization, and Year naturalized should be greyed out
For 1930 Year immigrated and Naturalization should be greyed out

**Comment by dfurber** [comment]
Thanks for that final clarification. It's on its way up now. Also broke the other census forms up into groups  like I did earlier for 1940.

**Comment by EveSnyder** [comment]
I saw that, thanks, it looks great by the way!
