### ISSUE TITLE
residence 1935 town and industry field names reverted to "To"

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#218]
Also occupation/industry in 1910 and 1920 because I the same problems impacted those records and I started to try to fix them last night.

**Comment by EveSnyder** [comment]
And occupation/industry for 1900 and 1930 too from this morning

**Comment by EveSnyder** [comment]
And Last name for 1940

**Comment by EveSnyder** [comment]
Currently the occupation field in Ithaca HF's data entry page is labeled "To"

**Comment by dfurber** [comment]
Closing because we fixed these back then but we forgot to close this.
