### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#219]
Dave, you mentioned previously that the administrator user-role was functionally the same as a super-user but what are the differences?  Should only you, me, and Bob be super-users, and the project coordinators for other projects be administrators?  If that is the case maybe it shouldn't be an option that is viewable except for those that are super-users.  Just as an FYI, not knowing the difference between the two roles we gave the project coordinators all the roles possible including super-user.  
Also could you make it so that the records entered by those with the editor role will not be publicly viewable until after they have been marked as reviewed?  Right now they are immediately public though they still technically need to be reviewed.  And, could the editor role be given the ability to review other people's records and make them publicly viewable?  It would be nice to have a level between census-taker and administrator for trusted volunteers to help with the reviewing process.  Lastly, if the developer role isn't used could you get rid of it?

**Comment by EveSnyder** [comment]
and also, just to confirm what we discussed yesterday, that the ability to bulk update should only be for those with administrator/super-user roles.

**Comment by dfurber** [comment]
Got it
