### ISSUE TITLE
phantom worker class responses for 1940 census

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#220]
I've noticed a few worker class labels as Pw or Gw rather than PW or GW.  When I edit the record the worker class disappears.  This happened last spring when you changed something for Naturalization but as far as I know you didn't change anything related to worker class.

**Comment by EveSnyder** [comment]
See for example-https://www.historyforge.net/census/1940/9530

**Comment by dfurber** [comment]
I think you worked your way around this before I fixed it. But the issue was the capitalization stuff we tried early was doing it to worker class, changing PW to Pw.
