### ISSUE TITLE
Controlled vocabularies reverted back to original

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#221]
After meticulously removing old controlled vocabulary from all 4 installations which took me hours, the controlled vocabulary has reverted back to what was there including all the Ita Italian, Ire Ireland, etc. These all show up as options again when someone types something in that starts with the same letter.  Sigh...

**Comment by dfurber** [comment]
Actually I think it's not as bad as that. What you're seeing is the auto-suggestions stored in the browser. Please shift-refresh and try again. If it still does it, it means there's a JavaScript error that is preventing it from using the controlled vocabulary. If so, then open the dev tools (command-option-i), make sure the Console is open, do the thing that doesn't work, and look for red. If you see red, send a screenshot or copy and paste the error.

**Comment by EveSnyder** [comment]
I checked the controlled vocabulary lists and the old terms are there.

**Comment by dfurber** [comment]
I do see a bunch of new terms that I can easily clear out once I figure out how they got in there:
["Argentine Republic South America", "Atlantic Ocean", "Austria Poland", "Austria Vienna", "Bermuda Islands", "Bohemia Czech", "Canada Dutch", "Canada English Nova Scotia", "Canada English Ontario", "Canada German", "Canada Irish", "Canada New Brunswick", "Canada Nova Scotia", "Canada Other", "Canada Scotch", "Canada Scotch Irish", "Don't Know", "Eng English", "England London", "English", "France Paris", "Ger German", "Germany   Baden", "Germany Berlin", "Germany Cologne", "Germany Hessia", "Germany Poland", "Germany Wurtenberg", "Holland (Russ)", "Hungary    Kiraly", "Hun Magyar", "Hun Slovak", "Iddesleigh England", "Ire English", "Ire Irish", "Ireland   Belfast", "Ireland Dublin", "Ireland English", "Ireland Free State", "Ireland Irish", "Ireland   Kerry County", "Ireland Longford", "Ireland North", "Ireland Northern", "Ireland (South)", "Ireland Tipperary", "Ireland   Unknown", "Ita Italian", "Left Blank", "London", "Long Island", "New England", "North Ireland", "Not Known", "Nova Scotia", "Nova Scotia Canada", "Nova Scotia Canada English", "Ontario Canada", "Ontario Canada English", "Philippine Islands", "Poland Austria", "Poland Austrian", "Poland German", "Poland Russia", "Poland Russian", "Prince Edward Island Canada", "Quebec Canada", "Rep Of Lithuania", "Romania    Szilagyi County", "Russia Poland", "Russ Polish", "Russ Yiddish", "Scot English", "Scot Scotch", "South Ireland", "Swed Swedish", "Swit German", "Syria Sado", "Taken From Almshouse", "Turk As Syrian", "Wales Eng", "Wales Welsh"]

**Comment by EveSnyder** [comment]
Those were all there originally from what was entered on the census in Ithaca.  Most should be removed but there were some from the 1900 census related to Poland that should be kept but I'll have to get you the correct terminology.

**Comment by EveSnyder** [comment]
Keep German Poland, Austrian Poland, and Russian Poland.  These don't seem to be on your list so you probably already figured those out.

**Comment by EveSnyder** [comment]
Thanks!

**Comment by dfurber** [comment]
They came from here:
[Places of Birth](https://github.com/historyforge/historyforge/blob/master/db/Place%20of%20Birth.csv)

Could you sweep through it and send me a corrected list?

**Comment by EveSnyder** [comment]
I will.  When I culled the list for the testing partners I left a few on our HF site like Cape Colony.  I don't know if that should just go in as Africa (because that feels ridiculously reductionist) with a note about the actual pob in the individual record or if I should leave those few exceptions.  Do you have any thoughts?  I can also ask Bob.

**Comment by dfurber** [comment]
I think the controlled vocabulary should be standard across all testing partners, and that the original entry ought to be (have been) saved because they have historical value.

**Comment by EveSnyder** [comment]
Does IPUMS have a master list of some sort?  I think you found something else from IPUMS before-we use it for occupation codes but I can't figure out how to access a list of pobs.  All of those extraneous ones like Iddesleigh England were initially generated by our list.  According to the instructions to enumerators they were supposed to enter the country of origin and only in some cases the cities-like those that might have changed hands during war or international conflict.  This often confused enumerators who started writing it all down.  In some cases like many of those above where it fell outside the instructions I stuck the true POB as per the census in the notes and used the country in the pob field. I was trying to strike a balance between maintaining the original, making searches in HF easier, and eliminating the potential for mistakes.  No one would find Long Island if they were searching for POB New York...  Also having so many options in the controlled vocabulary makes it easier for new transcribers to choose the wrong option.  For example in several years the census asked for a differentiation between Northern Ireland and Irish Free State which led to Ireland North, Ireland Northern, North Ireland and Ireland listed with all the different counties.

**Comment by dfurber** [comment]
For controlled vocabulary I think a curated list from what we found in the census records was fine. I was more suggesting keeping the original entry in addition to it. That would add an extra step and entail some posthoc cleanup though.

**Comment by EveSnyder** [comment]
I just added Venezuela to the controlled vocabulary on Ithaca HF and the master list.  I'm wondering if any of our testing partners have added any others to theirs.  I'll email and ask them.

**Comment by EveSnyder** [comment]
I just updated the master list and it is good to go!

**Comment by EveSnyder** [comment]
Currently occupation or profession-whichever you had it for 1940-is labeled "To" in the Ithaca HF data entry page.
