### ISSUE TITLE
Auburn HF user login problem

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#225]
Laura Harkins, current email: leh45sixty@yahoo.com also had a problem using the email: befrank4me@hotmail.com (same account).  
From the Auburn HF project coordinator-At times, the email wasn't accepted, but mostly it's been a password error. We tried resetting the password a few times and she was able to login on her iPad for Friday's session, but not her computer. When she tried today, it wouldn't accept either email or password. This is the error message: 1 error prohibited this user from being saved. Then it states:email not found.

**Comment by dfurber** [comment]
Her record is fine and the login code isn't any different for you or me. Maybe she has trouble typing the password?
