### ISSUE TITLE
problem saving jrs

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#226]
One of our transcribers just told me that she entered a jr who was 3 months old and the record wouldn't save so she added 0 for age in years and the record saved.  After that we were able to remove the 0 for age in years and the record saved again.  I know other people are still having problems saving jrs even when they enter jr in the suffix field.  I think they have then entered Jr after the first name and been able to save the record.

**Comment by dfurber** [comment]
Right because it didn't want to let you duplicate the same name at the same address with the same age. Somehow when the age in years was absent, it was ignoring the age. I made it so that if the age is blank to use a 0 so he doesn't get confused with papa.
