### ISSUE TITLE
building merge function does not attach person to new building record it merely removes the old building from the person's record

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#235]
I had previously merged 211 Mechanic St with 411 Hillview Pl.  Today I edited one of the records of an individual from the 1910 Census and they disappeared from the building record.  I was able to pull up that individual's record and found that he was originally attached to 211 Mechanic St which no longer exists leaving the person unattached to any building.  So when the buildings were merged, the building the person was attached to disappeared rather than changed to the new building, meaning that anytime I edit a record of someone whose building was merged (there are quite a few) they will automatically lose their building attachment. 
I went in and added 411 Hillview Pl to all the members of that family and they all still appear to be residents of the building but when I went back in to check the building they were once again listed without a building.

**Comment by dfurber** [comment]
Should work now...
