### ISSUE TITLE
Can't edit/delete either of these duplicate records

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#241]
One of our Ithaca transcribers entered this record twice, I am unable to edit either to delete one and make a note in the other.
https://www.historyforge.net/census/1940/16294 (this is the one that should be deleted)
https://www.historyforge.net/census/1940/17041 (this is the one that should be kept)

**Comment by dfurber** [comment]
@EveSnyder Are you logged in? I just deleted 16294 no problem..

**Comment by EveSnyder** [comment]
Yes, it gave me the white we're sorry something went wrong screen and just did again when I tried to edit the other record which I need to add a note to. Weird huh?

**Comment by dfurber** [comment]
I just added a note that says "This is a note!"

**Comment by EveSnyder** [comment]
Thanks I changed it.  Yay, I can edit records again!
