### ISSUE TITLE
Problem with how HF constitutes families/households in 1940 census

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#243]
Because 1940 only has a single household number rather than the dwelling number followed by the family number of the other census years, it seems to be creating groups of family members underneath an individual's records that don't belong together.  For example, see the family members listed under Robert Updike of Enfield's record: https://www.historyforge.net/census/1940/17124
There are several records many of which include people who live in Ithaca.  I think it is pulling from the family id # only since there is no dwelling number and no address on this record (there were no addresses in the census for Enfield for 1940-we'll have to figure those out later).

**Comment by dfurber** [comment]
Aha. I changed it to use the family id and within + or - 1 census sheet. If building is present, add the building id. Otherwise add dwelling number.
