### ISSUE TITLE
Change the fields home-maker, radio set, live on farm, speaks English and veteran to a click box for Yes

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#34]

**Comment by dfurber** [comment]
Done - check please that I got all the ones you wanted, especially on the non-1930 years.

**Comment by EveSnyder** [comment]
Will do.  I don't think we need a period after "This person is foreign born" on the 1930 data entry form.

**Comment by EveSnyder** [comment]
Click boxes for 1900 look good
for 1910 I'm going to have to ask Bob (on the one hand it doesn't matter since its done but on the other hand, its different from all the other years which looks weird and inconsistent).
for 1920 I think it should just say "Yes" to the right of the box (like you have in 1900 and 1930)
for 1930 - looks good just no period after foreign born (same for the other years).  Also, I think "Attended School" should be changed to "Attended school?" for consistency.

**Comment by dfurber** [comment]
Sorry didn't see the replies until just now. Did those things. Closing.
