### ISSUE TITLE
photos-doubled, if you try to remove one they both delete

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#39]

**Comment by dfurber** [comment]
Yeah don't do that - they didn't get upload twice. I just fixed it. Do you remember which ones you accidentally killed?

**Comment by EveSnyder** [comment]
I had saved it to my computer just in case before I deleted it and was able to add it back.

**Comment by dfurber** [comment]
The photo is in there once but linked to the building twice.
