### ISSUE TITLE
Naturalization status on 1930 results page

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#42]
"N" "Na" "NA" "and "Naturalized"  disappear when you edit something in an individual's record.  "na" seems to be the correct one.
"Al" "AL" and "Alien" are also incorrect, "al" is correct
"Pa" "PA" "Papers" are incorrect, "pa" is correct
"Un" is incorrect, "unknown" is correct

**Comment by dfurber** [comment]
Done. Please disregard my email from earlier.
