### ISSUE TITLE
individual results page-could you change it so if boxes are not checked it reads as blank

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#44]
Currently if the box isn't checked the individual results page interprets that as a no, but it should really be a blank.

**Comment by dfurber** [comment]
@EveSnyder I think this is done, or else I don't understand and need more clarification, such as an example.

**Comment by EveSnyder** [comment]
I think the fields that currently say blank used to say no but they should probably just be blank because the check box covers both "no" responses and blank fields where there isn't a response.  i.e. https://www.historyforge.net/census/1930/9956
