### ISSUE TITLE
1920 census individual result page missing "mother tongue" info

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#46]
I noticed that on the results page for this and several other individuals the "mother tongue" of the father and mother says blank even though that information is recorded on the data entry page and  shows on the results page for all the individuals on the census sheet.
https://www.historyforge.net/census/1920/2571  
I also noticed one case where mother tongue is listed on the data entry page but there was nothing listed for mother tongue on the results page but after I opened it to check and hit save the individual results page then said "blank" for mother tongue.

**Comment by dfurber** [comment]
Fixed...
