### ISSUE TITLE
tried to remove 2 historic markers but it wouldn't let me

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#48]
I got "we're sorry something went wrong, if you are the application owner check the logs for more information"  I'd like to delete both of these records, they are the only two markers on HF and as such  they don't reflect well on the project.
https://www.historyforge.net/buildings/4
https://www.historyforge.net/buildings/5

**Comment by dfurber** [comment]
Where this is going now that there is a new Photographs section is that, once I make a way to view photos on the map, you can remove the non-buildings from the building database.

**Comment by EveSnyder** [comment]
Excellent, thanks!

**Comment by dfurber** [comment]
I fixed the underlying issue and deleted the markers.
