### ISSUE TITLE
home ownership information for non heads of household

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#49]
We had changed it so that you could only enter the home ownership information for heads of household to make sure that people didn't enter it in all the records, now we have come across some records in 1930 where the wife/mother-in-law, father, etc is the home owner but not the head of household.  So far we are entering the home ownership info in the head's record and then making a note, but now we realize maybe we should not have it restricted this way, any thoughts?

**Comment by dfurber** [comment]
Is it just the homeownership question or all of the ones tied to Head?

**Comment by EveSnyder** [comment]
I'm pretty sure its just home owneship.

**Comment by dfurber** [comment]
I just removed owned or rented's dependency on head for 1930.
