### ISSUE TITLE
1930 filters include pob code for father and mother

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#50]
This is no longer a field, however, so there is no information in the database to filter on.

**Comment by dfurber** [comment]
So should it be removed from the census form as well?

**Comment by dfurber** [comment]
I think I've gotten confused as to where you need them and don't need them. So they don't belong on 1930?

**Comment by EveSnyder** [comment]
POB code is only on the 1930 census but we weren't using it for mother and father so they shouldn't be there.  Technically there is no pob code- according to Stephen Morse's website what we're calling pob code is for native language (foreign born) or state of birth (US born).  The other two that we were callling pob father and pob mother were for country of birth and citizenship but again we didn't have anyone input those.  https://stevemorse.org/census/abc.html

**Comment by dfurber** [comment]
Done!
