### ISSUE TITLE
Mill/Court Street

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#53]
If you search for Mill Street under street address in buildings nothing comes up but when you search on Court Street you get results for Court and Mill.  Shouldn't Mill Street come up in its own search?  Also, should we change all Mill Street addresses to Court Street and implement a policy of using the current street name but including the old one in the notes field if that's how it was enumerated?

**Comment by dfurber** [comment]
This is a duplicate of issue #15
