### ISSUE TITLE
Worker status

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#54]
From when we changed the data entry page I just noticed that worked status was affected in the same way that naturalization status was-where it shows up differently than others on the results page and when you go into the record it disappears
In some cases it shows as "0"- as in zero instead of O for Own Account.
Also as Emp instead of E
Worker instead of W

**Comment by dfurber** [comment]
I changed the 0, Emp, and Worker to their proper OA, E, and W
