### ISSUE TITLE
Employment Status for 1910, 1920 and 1930 data entry pages

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#55]
Change category called "Employment" in 1910 and 1920 and "Worker Status" in 1930 to "Employment Status" in the data entry form for all 3 census years.
Change the option for Own Account on the 1930 data entry page to OA.
[There is no similar category in 1900]

**Comment by dfurber** [comment]
Please check - I think I got it.

**Comment by dfurber** [comment]
Reopen as needed please.
