### ISSUE TITLE
Temporarily disable "add building" for 1920

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#56]
At this point we've probably got all the buildings and then some in HF.  I'm giving people directions not to add any buildings for this reason, however, I want to include instructions for add building in the pop up help text for the future.  Most of our regular transcribers will probably remember not to add a building but new people might not. Is there a way to temporarily disable add building for 1920 until we're done entering the records?

**Comment by dfurber** [comment]
Done. Now I await the bug report that the "add building" checkbox is missing for 1920 :)
