### ISSUE TITLE
Radio button other - focus issues

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#7]
When you tab across the fields and you enter race=white and tab again it takes you to the field where you can enter an additional racial category rather than bringing you straight to age.

**Comment by dfurber** [comment]
When you select a radio button other than other, then Tab should skip over "Other". When you select the "other" radio button, then focus on Other text field.

**Comment by EveSnyder** [comment]
I tried it again, I entered Mexican American and hit tab and instead of going to the age field it went to the field to allow me to enter in a racial category other than what was listed there.

**Comment by EveSnyder** [comment]
PS Bob just explained what a radio button is:-) Boy was I confused

**Comment by dfurber** [comment]
Sorry about the confusion! Please try now. If you select "Other" it should focus on the Other: text field, otherwise the text field will be disabled. When you click a not-other radio button and something is filled into the Other, then it will get removed because no longer applies.
