### ISSUE TITLE
Buildings Page - highlight of nearby buildings addresses and points

### ISSUE THREAD

**Issue by spbissen** [historyforge/historyforge-old#71]
On a Buildings page, on the right-side bottom, where the nearby building addresses are listed, if one were to mouse-over the address, you would see the corresponding point on the map turn from red to blue.  Also if one mouses-over a point on the map, it turns blue but all the address below are highlighted instead of just the corresponding address block for that point.

**Comment by dfurber** [comment]
Thanks Steve for noting it's AWOL status. I just brought it back!
