### ISSUE TITLE
Way for users to get in touch with us if they notice something incorrect

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#8]
Could we have a place on as many pages as possible-at least every individual record page and each general census year page for people to alert us that there is a problem or for any reason-maybe a link to a form of some sort that they can fill out that includes a way to note the specific record in cases specific to an individual record.  I think asking them to type out the yeaar, ED, page and sheet # as well as the name might be too much, maybe they could be prompted to include the url to the individual record which has the id # for example - https://www.historyforge.net/census/1930/9939

**Comment by dfurber** [comment]
Look out for the new flag system
