### ISSUE TITLE
Can't filter by profession code

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#81]
I think its because the filter is called occupation code but the field is called profession code.

**Comment by EveSnyder** [comment]
I noticed that in 1920 HF its called employment code in both the field and filter.  Let's go with IPUMS and call it occupation code everywhere in 1920 and 1930 and 1940 when that's available.  https://usa.ipums.org/usa-action/variables/OCC#codes_section
Also for some reason even though it has the same name in 1920 I wasn't able to pull up the results of a seach for a specific code that I know was in the database.

**Comment by dfurber** [comment]
I think this is fixed- please check and update.

**Comment by EveSnyder** [comment]
1920 works but for 1920 its called employment code in both the fields and the data entry page but the name needs to be changed to occupation code in both fields (that's what IPUMS has).  
1930 does not work.  In 1930 the field on the data entry page is occupation code but the field in the fields on the search results page is called profession code, which could be why it doesn't work.  Also, there's another field called coded occupation name and coded industry name which shouldn't be there.
1940 works.

**Comment by dfurber** [comment]
How is it now? I think it was tied in with our labeling issues.

**Comment by EveSnyder** [comment]
1920 works but under filters its still called employment code (its labeled correctly in the fields).
1930 does not work though it is labeled correctly as occupation code in the fields and filter.

**Comment by dfurber** [comment]
Aha. I fixed 1920. Problem with 1930 was that it shouldn't have been there. It's handled differently as "Coded Occupation" along with "Coded Profession."

When I get the master spreadsheet with fields and labels, I may rework the filters too to feed from the same source.
