### ISSUE TITLE
Naturalization status-1920, 1910

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#83]
We had this problem for 1930 (see closed issue #42)
Can you fix for 1920
"N" "Na" "NA" "and "Naturalized" disappear when you edit something in an individual's record. "na" seems to be the correct one.
"Al" "AL" and "Alien" are also incorrect, "al" is correct
"Pa" "PA" "Papers" are incorrect, "pa" is correct
"Un" and "Unknown" are incorrect, "unknown" is correct
Also, for 1910 the opposite appears to be true (see below), can you fix so it is the same as 1920 and 1930 without losing any data-we already lost a lot when we separated the pob from mother tongue.
"al" is incorrect, "Al" is correct
"na" is incorrect, "Na" is corrrect
"pa" is incorrect, (I'd say "Pa" is correct but I didn't see any)
"unknown" is correct (I didn't see any other options under foreign born).

**Comment by dfurber** [comment]
@EveSnyder This seems to have been fixed in the meantime...

**Comment by EveSnyder** [comment]
Yes I did it manually.
