### ISSUE TITLE
Naturalization status 1900

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#84]
The 1900 data entry page doesn't have a drop down menu option for naturalizartion status.  The options should be the same as the standard for 1910-1930.  Can that be done without losing the data already entered in those fields (its not standardized, just whatever people wrote in)
From what I can tell it looks like 
unknown=unknown, Unknown, Un, un, u
papers=Pa
naturalized=Naturalized, Nat, NA, Na, na
alien=Alien. Al, AL, 
Some are also listed as left blank, Yes, and yes.  For the latter two I can go in and double check those and try to figure them out and change them.
Could you archive the data before changing this, or download it to csv to make sure we don't lose anything in the transition?

**Comment by dfurber** [comment]
@EveSnyder Nothing will be lost in the transaction. I'll need to correct the choices in the database, however.

**Comment by dfurber** [comment]
@EveSnyder Also  there are some "Yes" answers - you should probably fix those manually.

**Comment by EveSnyder** [comment]
Of course it does:-)   That's on the census. I'll have to figure out wheyther I should assume that means Na or not.

**Comment by EveSnyder** [comment]
As per a discussion with Bob I changed those Yes's to Naturalized.
