### ISSUE TITLE
1920 Census race and sex can't be left blank

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#85]
In some cases the enumerator left these fields blank but it won't let me save.  Same for marital status.

**Comment by dfurber** [comment]
I know there was a reason why we made them required even though it has the "left blank" option. But I removed it.

**Comment by EveSnyder** [comment]
Oh right, we made them required because a lot of people weren't entering them by mistake.  Leave it removed since somewere actually left blank.
