### ISSUE TITLE
1940 census occupation codes

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#92]
In case this is helpful-this is not a numerical field.
Three-figure occupation code followed by a two-figure industry code and a 1-figure worker class code. 
The occupation can contain a “V” or “X” as well as numbers.
The industry code can contain a “V” or “X” as well as numbers.
The one-digit class code only has the options 1-6.

**Comment by dfurber** [comment]
Not sure what the todo is here - I did fix the code validation on a different ticket.

**Comment by EveSnyder** [comment]
It works now
