### ISSUE TITLE
Remove "Map It" page from the navigation bar

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#97]
Currently this maps everything if people click on it which isn't useful.  What we really need here is a link to a map repository in the "near" future.

**Comment by dfurber** [comment]
I renamed it "The Forge" using "edit main menu links" on admin menu. I didn't remove it because otherwise how will you get to it?

**Comment by EveSnyder** [comment]
Okay if you think this could be useful. At least most people won't click it now by mistake with the name change.
