### ISSUE TITLE
"Building Name"

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#98]
On building results page remove building name from left side and replace with address, building name can be a field displayed on the right with the other fields.  
In individual building records-only use building name if the building has a name, don't have the address automatically populated in that field.  Display building address at top of each record rather than building name.  Have building address at top in regular form, i.e. 202 N Aurora rather than Aurora N - #202.

**Comment by dfurber** [comment]
Should be done now, lemme know if I missed something.
