### ISSUE TITLE
1940 field name changes on 1940 results page

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#99]
Can you rername the field for Family no to Household no
Change Had job to Has work
Change no work code
Change private hours worked to hours worked
Change employment status to worker class
Change full time weeks to weeks worked 1939
Change Had unearned income to other income source
Change veteran to veteran/veteran-related
Change veteran dead to veteran deceased
Change soc sec to  SS#
Add in OA/RR ins
Remove deductions
Change usual profession to usual occupation

**Comment by dfurber** [comment]
I think the issue is that wherever you are looking isn’t pulling in the correct labels, so you’re seeing the underlying field names.

**Comment by EveSnyder** [comment]
I'm looking at the fields listed under the fields tab on the main search results page for 1940, the page you get when you click People, then 1940 US Census.

**Comment by EveSnyder** [comment]
I meant to say remove no work code from the fields
